'use client';

import { useRef } from 'react';
import { FiClipboard, FiZap, FiCheck, FiDownload, FiTrash2 } from 'react-icons/fi';

export default function AssignmentGuidanceDisplay({ guidance, onDelete, onDownload }) {
  const contentRef = useRef(null);

  return (
    <div className="bg-white/60 dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden border border-white/70 dark:border-gray-700 backdrop-blur-lg">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-purple-700 dark:from-purple-700 dark:to-purple-800 text-white p-6 flex justify-between items-start">
        <div className="flex-1">
          <h3 className="text-lg font-semibold mb-1 flex items-center gap-2"><FiClipboard size={18} /> {guidance.fileName}</h3>
          <p className="text-purple-100 text-sm">
            Generated on {guidance.processedAt.toLocaleDateString()} at {guidance.processedAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => onDownload(guidance)}
            className="px-3 py-1 bg-purple-500 hover:bg-purple-600 rounded text-white text-sm transition-colors flex items-center gap-1"
          >
            <FiDownload size={14} /> Download
          </button>
          <button
            onClick={() => onDelete(guidance.id)}
            className="px-3 py-1 bg-red-500 hover:bg-red-600 rounded text-white text-sm transition-colors flex items-center gap-1"
          >
            <FiTrash2 size={14} /> Delete
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        <div className="mb-4 p-4 bg-blue-50/70 dark:bg-blue-900/20 border border-blue-200/70 dark:border-blue-800 rounded-lg flex items-start gap-3 backdrop-blur-md">
          <FiZap size={18} className="text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-blue-900 dark:text-blue-300 font-semibold">
            This is personalized guidance to help you approach the assignment, not a complete solution.
          </p>
        </div>
        <div
          ref={contentRef}
          className="prose prose-sm dark:prose-invert max-w-none text-gray-800 dark:text-gray-200 whitespace-pre-wrap leading-relaxed"
        >
          {guidance.guidance}
        </div>
      </div>

      {/* Footer */}
      <div className="bg-gray-50/75 dark:bg-gray-700/50 p-4 border-t border-gray-200/70 dark:border-gray-700 flex justify-between text-sm text-gray-600 dark:text-gray-400">
        <span>Assignment Guidance Generated by AI</span>
        <span className="flex items-center gap-2"><FiCheck size={14} /> Personalized for {guidance.studentName}</span>
      </div>
    </div>
  );
}
