'use client';

import { useRef } from 'react';

export default function NoteDisplay({ note, onDelete, onDownload }) {
  const contentRef = useRef(null);

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden border border-gray-200 dark:border-gray-700">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-700 dark:from-blue-700 dark:to-blue-800 text-white p-6 flex justify-between items-start">
        <div className="flex-1">
          <h3 className="text-lg font-semibold mb-1">📄 {note.fileName}</h3>
          <p className="text-blue-100 text-sm">
            Processed on {note.processedAt.toLocaleDateString()} at {note.processedAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => onDownload(note)}
            className="px-3 py-1 bg-blue-500 hover:bg-blue-600 rounded text-white text-sm transition-colors"
          >
            ⬇️ Download
          </button>
          <button
            onClick={() => onDelete(note.id)}
            className="px-3 py-1 bg-red-500 hover:bg-red-600 rounded text-white text-sm transition-colors"
          >
            🗑️ Delete
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        <div
          ref={contentRef}
          className="prose prose-sm dark:prose-invert max-w-none text-gray-800 dark:text-gray-200 whitespace-pre-wrap leading-relaxed"
        >
          {note.notes}
        </div>
      </div>

      {/* Footer */}
      <div className="bg-gray-50 dark:bg-gray-700/50 p-4 border-t border-gray-200 dark:border-gray-700 flex justify-between text-sm text-gray-600 dark:text-gray-400">
        <span>Study Material Generated by AI</span>
        <span>✓ Personalized for {note.studentName}</span>
      </div>
    </div>
  );
}
