'use client';

import { useRef, useState, useEffect } from 'react';
import { FiDownload, FiShare2, FiCheck, FiFile, FiTrash2 } from 'react-icons/fi';

export default function NoteDisplay({ note, onDelete, onDownload }) {
  const contentRef = useRef(null);
  const [isDark, setIsDark] = useState(false);

  useEffect(() => {
    const checkDark = () => setIsDark(document.documentElement.classList.contains('dark'));
    checkDark();
    const observer = new MutationObserver(checkDark);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);

  return (
    <div className="bg-white/25 dark:bg-gray-800 rounded-lg shadow-md overflow-hidden border border-white/40 dark:border-gray-700 backdrop-blur-md">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-700 dark:from-blue-700 dark:to-blue-800 text-white p-6 flex justify-between items-start">
        <div className="flex-1">
          <h3 className="text-lg font-semibold mb-1 flex items-center gap-2"><FiFile size={18} /> {note.fileName || note.title || 'Study Notes'}</h3>
          <p className="text-blue-100 text-sm">
            Processed on {(note.processedAt ? new Date(note.processedAt) : new Date(note.date || new Date())).toLocaleDateString()} at {(note.processedAt ? new Date(note.processedAt) : new Date(note.date || new Date())).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => onDownload(note)}
            className="px-3 py-1 bg-blue-500 hover:bg-blue-600 rounded text-white text-sm transition-colors flex items-center gap-1"
          >
            <FiDownload size={14} /> Download
          </button>
          <button
            onClick={() => onDelete(note.id)}
            className="px-3 py-1 bg-red-500 hover:bg-red-600 rounded text-white text-sm transition-colors flex items-center gap-1"
          >
            <FiTrash2 size={14} /> Delete
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        <div
          ref={contentRef}
          className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap leading-relaxed"
          style={{ color: isDark ? '#ffffff' : '#000000' }}
        >
          {note.notes || note.content}
        </div>
      </div>

      {/* Footer */}
      <div className="bg-gray-50/30 dark:bg-gray-700/50 p-4 border-t border-gray-200/40 dark:border-gray-700 flex justify-between text-sm text-gray-600 dark:text-gray-400">
        <span>Study Material Generated by AI</span>
        <span className="flex items-center gap-2"><FiCheck size={14} /> Personalized Learning</span>
      </div>
    </div>
  );
}
